PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbpprop: <http://dbpedia.org/property/>

CONSTRUCT
{
    ?tunefindSong rdf:sameAs ?chartSong .
    ?chartSong rdf:sameAs ?tunefindSong .  
}
WHERE
{
	?tunefindSong a dbpedia-owl:Song ;
                dbpedia-owl:artist ?tunefindArtist ;
                rdfs:label ?tunefindSongLabel .
  
  	#?tunefindArtist a dbpedia-owl:MusicalArtist ;
    #              rdfs:label ?tunefindArtistLabel .
  
    FILTER(STRSTARTS(STR(?tunefindSong), "http://imn.htwk-leipzig.de/pbachman/ontologies/tunefind#"))
  
  	?chartSong a dbpedia-owl:Song ;
               dbpedia-owl:artist ?chartArtist ;
               rdfs:label ?chartSongLabel .
  
   	#?chartArtist a dbpedia-owl:MusicalArtist ;
    #            rdfs:label ?chartArtistLabel .
  
    FILTER(STRSTARTS(STR(?chartSong), "http://imn.htwk-leipzig.de/pbachman/ontologies/charts#"))
  

    FILTER(lcase(STR(?tunefindSongLabel)) = lcase(STR(?chartSongLabel)))
    #FILTER(lcase(STR(?tunefindArtistLabel)) = lcase(STR(?chartArtistLabel)))
}