PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX : <http://imn.htwk-leipzig.de/pbachman/ontologies/imdb#>

SELECT ?date
WHERE
{
	?m a dbpedia-owl:Film ;
       imdb:releasedIn ?r.

    ?r dbpedia-owl:publicationDate ?date

    FILTER (?date >= "2000-01-01T00:00:00Z"^^xsd:dateTime)
}
ORDER BY ?date